"""empty message

Revision ID: 3354fc98102c
Revises: a267c55d355f
Create Date: 2022-02-21 19:56:10.556959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3354fc98102c'
down_revision = 'a267c55d355f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('subtitle', sa.Boolean(), nullable=False))
    op.add_column('movies', sa.Column('dubbed', sa.Boolean(), nullable=False))
    op.add_column('movies', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('series', sa.Column('subtitle', sa.Boolean(), nullable=False))
    op.add_column('series', sa.Column('dubbed', sa.Boolean(), nullable=False))
    op.add_column('series', sa.Column('views', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'created_at')
    op.drop_column('series', 'views')
    op.drop_column('series', 'dubbed')
    op.drop_column('series', 'subtitle')
    op.drop_column('movies', 'created_at')
    op.drop_column('movies', 'views')
    op.drop_column('movies', 'dubbed')
    op.drop_column('movies', 'subtitle')
    # ### end Alembic commands ###
