"""gender is unique

Revision ID: 6d6aad66df42
Revises: 887e10cfd023
Create Date: 2022-03-02 14:22:31.255027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6aad66df42'
down_revision = '887e10cfd023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genders', ['gender'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genders', type_='unique')
    # ### end Alembic commands ###
