"""empty message

Revision ID: 887e10cfd023
Revises: 9cfdaef069b9
Create Date: 2022-02-25 11:18:16.658951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887e10cfd023'
down_revision = '9cfdaef069b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('classification', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('released_date', sa.DateTime(), nullable=False))
    op.add_column('profiles', sa.Column('kids', sa.Boolean(), nullable=True))
    op.add_column('series', sa.Column('classification', sa.Integer(), nullable=False))
    op.add_column('series', sa.Column('released_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'released_date')
    op.drop_column('series', 'classification')
    op.drop_column('profiles', 'kids')
    op.drop_column('movies', 'released_date')
    op.drop_column('movies', 'classification')
    # ### end Alembic commands ###
